language: ruby

rvm:
  - 2.2.4

before_install:
  - gem install bundler --version 1.6.1
  - bundle install

env:
  - DB=postgresql
  - "RAILS_VERSION=~>4"
  - "RAILS_VERSION=~>5"
  - "RAILS_VERSION=master"

before_script:
  - rake app:db:create
  - rake app:db:migrate
  - rake app:db:test:prepare

